name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ 设置 Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # 3️⃣ 设置 Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 4️⃣ 安装 pnpm 并构建前端
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        working-directory: ./frontend
        run: pnpm build

      # 5️⃣ 构建 Go 后端
      - name: Build Go backend
        run: go build -o server ./main.go

      # 6️⃣ 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .

      # 7️⃣ 登录 GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # 8️⃣ 推送 Docker 镜像
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE_NAME

      # 9️⃣ 输出镜像信息
      - name: Image digest
        run: |
          echo "Full-stack image: $DOCKER_IMAGE_NAME"
